import SpaceCharacter, {CharacterBanner,CharacterArt} from "./components/SpaceCharacter";
import IntroLoader from "./components/IntroLoader";
import CharacterHero, {CharacterCheckpoint} from "./components/CharacterHero";
import SiteMotion from "./components/SiteMotion";
import ProfessionalApps from "./components/ProfessionalApps";
import WebsiteGallery from "./components/WebsiteGallery";
import PhotoGallery, { Photo, PhotoHighlights } from "./components/PhotoGallery";
import {useEffect, useRef, useState, type ReactNode} from 'react';
import {BrowserRouter, Routes, Route, Link, NavLink, useLocation, useParams, Navigate} from 'react-router-dom';
import {ArrowRight, ArrowUpRight, Menu, X, Coffee, Code2, Layers, Smartphone} from 'lucide-react';
import {projects, services} from './PortfolioContent';
import content from './content.json';
import './multipage.css';
const links:Record<string,string>=content.links;
const slugs=['american-electric-power','walmart-receiving','hcsc','walmart-seller-center'];
const pages=[['Home','/'],['About','/about'],['Experience','/experience'],['Connect','/contact']];
function Pill({to,children,dark=false}:{to:string;children:ReactNode;dark?:boolean}){return <Link className={`ma-pill ${dark?'dark':''}`} to={to}><span className="ma-roll"><span>{children}</span><span aria-hidden="true">{children}</span></span><span className="ma-arrow"><ArrowRight size={17}/></span></Link>}
function Badge({n,children}:{n:string;children:ReactNode}){return <div className="ma-badge"><span>{n}</span><p>{children}</p></div>}
function Header(){
 const dialog=useRef<HTMLDialogElement>(null);const trigger=useRef<HTMLButtonElement>(null);const [open,setOpen]=useState(false);const location=useLocation();
 const close=()=>{dialog.current?.close();setOpen(false)};
 useEffect(()=>{dialog.current?.close();setOpen(false)},[location.pathname,location.hash]);
 useEffect(()=>{if(!open)return;const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=previous}},[open]);
 return <><header className="ma-header"><nav aria-label="Main navigation"><Link className="ma-logo" to="/" aria-label="Aaron Ramírez home">AR</Link><div className="ma-navlinks">{pages.map(([name,path])=><NavLink key={path} to={path} end={path==='/'}>{name}</NavLink>)}</div><div className="ma-navright"><Pill to="/contact" dark>Let’s build something</Pill></div><button ref={trigger} className="ma-menu" aria-label="Open navigation" aria-expanded={open} aria-controls="mobile-navigation" onClick={()=>{dialog.current?.showModal();setOpen(true)}}><Menu size={20}/></button></nav></header>
 <dialog id="mobile-navigation" ref={dialog} className="ma-menu-overlay" aria-label="Site navigation" onCancel={close} onClose={()=>{setOpen(false);trigger.current?.focus()}}><div className="ma-overlay-top"><span>AR<span className="ma-overlay-dot">.</span></span><button aria-label="Close navigation" onClick={close}><X size={25}/></button></div><div className="ma-overlay-main"><p>EXPLORE THE SITE</p><nav aria-label="Mobile navigation">{pages.map(([name,path],i)=><Link key={path} to={path} onClick={close} aria-current={location.pathname===path?'page':undefined} style={{animationDelay:`${100+i*65}ms`}}><span className="ma-overlay-number">0{i+1}</span><span>{name}</span><ArrowUpRight/></Link>)}</nav></div><div className="ma-overlay-bottom"><span>HAVE SOMETHING IN MIND?</span><a href="mailto:rl.aaron4@gmail.com">Let’s talk <ArrowUpRight size={20}/></a><p>Aaron David Ramírez Lezama<br/>React Native & Frontend Engineer</p></div></dialog></>
}
function RouteEffects(){const {pathname,hash}=useLocation();useEffect(()=>{const title=pathname==='/'?'React Native & Frontend Engineer':pathname.split('/').filter(Boolean).map(p=>p.replaceAll('-',' ')).join(' / ');document.title=`Aaron Ramírez — ${title.charAt(0).toUpperCase()+title.slice(1)}`;if(hash){requestAnimationFrame(()=>{const element=document.getElementById(hash.slice(1));if(element instanceof HTMLDetailsElement)element.open=true;element?.scrollIntoView()})}else{window.scrollTo({top:0,behavior:'instant' as ScrollBehavior});document.getElementById('page-content')?.focus({preventScroll:true})}},[pathname,hash]);return null}
function PageIntro({n,label,title,description}:{n:string;label:string;title:string;description:string}){return <div className="ma-page-intro"><Badge n={n}>{label}</Badge><h1>{title}</h1><p>{description}</p></div>}
function Home(){return <><CharacterHero/><section className="ma-intro ma-wrap"><Badge n="01">The person behind the products</Badge><h2>Thoughtful architecture.<br/>Real-world results.</h2><div className="ma-intro-grid"><div className="ma-portrait"><img src="/aaron-removebg-preview.png" width="421" height="559" alt="Aaron Ramírez" loading="lazy"/></div><div className="ma-intro-copy"><p>10+ years delivering enterprise mobile and frontend applications for Walmart, IBM/AEP, and HCSC. I build shared foundations, improve performance, and help distributed teams deliver with confidence.</p><Pill to="/about">Meet Aaron</Pill></div><figure className="ma-home-event"><Photo index={7}/><figcaption>Meeting the developer community, beyond the screen.</figcaption></figure></div></section><div className="ma-wrap ma-home-apps"><ProfessionalApps/></div><FreelanceSection/><PhotoHighlights/><CharacterBanner/><section className="ma-wrap ma-home-links"><Badge n="03">A little more context</Badge><h2>Good work starts<br/>with good people.</h2><div><Link to="/experience"><span>01 / THE JOURNEY</span><h3>Explore my experience</h3><ArrowUpRight/></Link><Link to="/about#community"><span>02 / BEYOND THE CODE</span><h3>Code, coffee & community</h3><ArrowUpRight/></Link></div></section></>}
function FreelanceSection(){
  const offerings=[
    {icon:Smartphone,title:'Build your mobile & web product',description:'From an early idea to a working product. React Native with Expo and EAS for iOS and Android, plus React frontends built to grow.',deliverable:'MVPs · New features · App launches'},
    {icon:Layers,title:'Make your app stronger',description:'Untangle architecture, find performance bottlenecks, and turn a growing codebase into something your team can move forward with.',deliverable:'Architecture reviews · Performance · Modernization'},
    {icon:Code2,title:'Bring experience to your team',description:'Hands-on engineering and technical direction alongside your developers, with thoughtful reviews and knowledge shared along the way.',deliverable:'Technical leadership · Code reviews · Mentoring'},
  ];
  return <section id="freelance" className="ma-freelance" aria-labelledby="freelance-title"><div className="ma-wrap">
    <div className="ma-freelance-heading"><div><Badge n="↗">Freelance & consulting</Badge><h2 id="freelance-title">Your ambition.<br/><em>My hands on the build.</em></h2></div><p>A focused project or an extra pair of experienced hands. Work directly with me to bring your next mobile or web product to life.</p></div>
    <div className="ma-freelance-services">{offerings.map(({icon:Icon,title,description,deliverable},i)=><article key={title}><div className="ma-freelance-icon"><Icon size={25}/><span>0{i+1}</span></div><h3>{title}</h3><p>{description}</p><span className="ma-freelance-deliverable">{deliverable}</span></article>)}</div>
    <WebsiteGallery/><div className="ma-freelance-start"><div><span className="ma-freelance-label">LET’S FIND THE RIGHT FIT</span><h3>What are you working on?</h3><p>Tell me about your idea, timeline, and what you need. We’ll start with a conversation and shape the scope together.</p></div><a className="ma-pill" href="mailto:rl.aaron4@gmail.com?subject=Let%E2%80%99s%20talk%20about%20a%20freelance%20project&body=Hi%20Aaron%2C%0A%0AMy%20project%3A%20%0ATimeline%3A%20%0AWhat%20I%20need%20help%20with%3A%20%0A"><span>Tell me about your project</span><span className="ma-arrow"><ArrowUpRight size={17}/></span></a></div>
  </div></section>
}
function ProjectGrid(){return <div className="ma-project-grid">{projects.map((p,i)=><Link key={p.name} to={`/projects/${slugs[i]}`} className={`ma-project-tile ${p.color}`}><div className="ma-project-art"><span>{p.company}</span><strong>{p.metric}</strong><p>{p.metricLabel}</p><span className="ma-project-arrow"><ArrowUpRight/></span></div><p>{p.type}</p><h2>{p.name}</h2></Link>)}</div>}
function ProjectsPage(){return <div className="ma-wrap ma-projects-code-only"><section className="ma-code-project" id="github"><Badge n="↗">Code & learning</Badge><div className="ma-code-card"><Code2 size={38}/><div><span>REACT NATIVE · EXPO · FIREBASE</span><h2>MVP Boilerplate</h2><p>A hands-on starter from my “From Idea to App” talk: explore movie data, authentication, and navigation while building a React Native MVP.</p><a href="https://github.com/aaronrl25/mvpboilerplate" target="_blank" rel="noopener noreferrer">Explore the repository <ArrowUpRight size={17}/></a></div></div><a className="ma-code-profile" href={links.GitHub} target="_blank" rel="noopener noreferrer">More code on GitHub · @aaronrl25 <ArrowUpRight size={17}/></a></section></div>}
function ProjectPage(){const {slug}=useParams();const i=slugs.indexOf(slug||'');if(i<0)return <NotFound/>;const p=projects[i];const job=content.experience[p.detail];return <article className="ma-wrap ma-case"><Link className="ma-back" to="/projects">← All projects</Link><PageIntro n={`0${i+1}`} label={p.company} title={p.name} description={p.desc}/><div className={`ma-case-visual ${p.color}`}><strong>{p.metric}</strong><p>{p.metricLabel}</p><div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div></div><div className="ma-case-grid"><div><Badge n="01">My contribution</Badge><h2>{p.sub}</h2><p>{job.role}<br/>{job.date}</p></div><ul>{job.bullets.map(b=><li key={b}>{b}</li>)}</ul></div><div className="ma-case-bottom"><Pill to={`/experience#role-${p.detail}`}>View full experience</Pill><Pill to={`/projects/${slugs[(i+1)%slugs.length]}`} dark>Next project</Pill></div></article>}
function AboutPage(){return <><div className="ma-wrap"><PageIntro n="02" label="About Aaron" title="Engineer. Mentor. Community builder." description="Staff, Lead, and Senior React Native & Frontend engineer focused on enterprise-scale applications, engineering standards, and distributed teams."/><div className="ma-about-grid"><div className="ma-portrait"><img src="/aaron-removebg-preview.png" alt="Aaron Ramírez" width="421" height="559"/></div><div><Badge n="01">Mission briefing</Badge><h2>A decade in mobile.<br/>Always curious.</h2><p>My work spans Walmart’s Seller Center and fulfillment platforms, IBM/AEP’s field operations, and HCSC’s member experience. I combine React Native and React architecture with performance profiling, strong testing standards, and hands-on mentoring. I also use Claude and Cursor to accelerate delivery while keeping code quality central.</p><div className="ma-stats">{[['10+','Years in software'],['3','Teams adopting shared standards'],['5','Hackathon wins'],['200+','Chicago monthly attendees']].map(([n,t])=><div key={t}><strong>{n}</strong><span>{t}</span></div>)}</div></div></div><div className="ma-about-photo-strip"><figure><Photo index={2}/><figcaption>A little exploration between projects.</figcaption></figure><figure><Photo index={10}/><figcaption>Conversations and connections at Auth0 Camp AI.</figcaption></figure></div><section id="expertise" className="ma-expertise"><Badge n="02">What I bring</Badge><h2>From idea to everyday use.</h2>{services.map(([name,desc],i)=><div className="ma-service" key={name}><span>0{i+1}</span><h3>{name}</h3><p>{desc}</p><ArrowUpRight/></div>)}</section><section id="skills" className="ma-skills"><Badge n="03">Toolkit</Badge><div>{content.skills.map(([n,t])=><article key={n}><h3>{n}</h3><p>{t}</p></article>)}</div></section><section id="education" className="ma-skills"><Badge n="04">Education</Badge><div>{content.education.map(([degree,school])=><article key={degree}><h3>{degree}</h3><p>{school}</p></article>)}</div></section><section id="community" className="ma-community"><Badge n="05">Community & recognition</Badge><h2>Sharing what I learn.<br/>Building community.</h2><div>{content.community.map(([title,description])=><article key={title}><Coffee/><h3>{title}</h3><p>{description}</p>{title==='Podcast host'&&<a className="ma-community-video" href={links.YouTube} target="_blank" rel="noopener noreferrer">Watch on YouTube ↗</a>}</article>)}</div></section><CharacterArt/><PhotoGallery/></div></>}
function ExperiencePage(){return <div className="ma-wrap"><PageIntro n="03" label="Mission log" title="The work. The teams. The journey." description="10+ years of React Native and frontend engineering, from startup products to Staff-level marketplace development at Walmart. My roles, contributions, and results."/><CharacterCheckpoint kind="land" label="MISSION LOG / ENGINEERING" title="Built to take on the next challenge."/><figure className="ma-experience-photo"><Photo index={0}/><figcaption>Sharing ideas with the developer community.</figcaption></figure><ProfessionalApps/><div className="ma-experience">{content.experience.map((e,i)=><details key={`${e.company}-${i}`} id={`role-${i}`} open={i===0}><summary><span>{e.date}</span><div><h2>{e.role}</h2><p>{e.company}</p></div><span className="ma-plus">+</span></summary><div className="ma-experience-body"><ul>{e.bullets.map(b=><li key={b}>{b}</li>)}</ul><div className="tags">{e.tags.map(t=><span key={t}>{t}</span>)}</div></div></details>)}</div><a className="ma-resume" href={links.Resume} target="_blank" rel="noopener noreferrer">Résumé <ArrowUpRight size={18}/></a></div>}
function ContactPage(){return <div className="ma-wrap connect-page"><div className="connect-topline"><span>CONNECT / AARON RAMÍREZ</span><span>LET’S START A CONVERSATION <ArrowUpRight size={14}/></span></div><div className="connect-intro"><h1>Good things start<br/>with <em>hello.</em></h1><div className="connect-person"><Photo index={23}/><p>Aaron David Ramírez Lezama<span>React Native & Frontend Engineer</span></p></div></div><CharacterCheckpoint kind="smile" label="TRANSMISSION OPEN" title="Your next teammate, reporting in."/><div className="connect-main"><div className="connect-email-block"><span className="connect-label">HAVE A ROLE OR PROJECT IN MIND?</span><a className="connect-email" href="mailto:rl.aaron4@gmail.com"><span>rl.aaron4@gmail.com</span><ArrowUpRight/></a><p>Let’s talk about what you’re building, where you need help, and how I can contribute.</p><a className="connect-compose" href="mailto:rl.aaron4@gmail.com">Write me an email <ArrowUpRight size={17}/></a></div><div className="connect-details"><span className="connect-label">THE NEXT CHAPTER</span><p>Seeking Senior, Lead, or Staff-level React Native and Frontend roles. Bringing 10+ years of enterprise delivery, architecture, and engineering leadership.</p><a href="tel:+17737082882">+1 (773) 708-2882 <ArrowUpRight size={18}/></a></div></div><div className="connect-links">{['LinkedIn','GitHub','YouTube','Resume'].map((n,i)=><a key={n} href={links[n]} target="_blank" rel="noopener noreferrer"><span>0{i+1}</span><strong>{n==='Resume'?'Résumé':n}</strong><ArrowUpRight size={21}/></a>)}</div></div>}
function NotFound(){return <div className="ma-wrap ma-not-found"><PageIntro n="404" label="Off course" title="This page hasn’t landed yet." description="Let’s get you back to the portfolio."/><Pill to="/">Back home</Pill></div>}
function Footer(){const location=useLocation();return <footer className="ma-footer">{location.pathname!=='/contact'&&<div className="ma-footer-cta"><span>HAVE SOMETHING IN MIND?</span><h2>Let’s make it happen.</h2><Pill to="/contact">Start a conversation</Pill></div>}<div className="ma-footer-bottom"><Link to="/" className="ma-footer-name">Aaron Ramírez<span>®</span></Link><div>{pages.map(([n,p])=><Link to={p} key={p}>{n}</Link>)}</div><span>© {new Date().getFullYear()} Aaron David Ramírez Lezama</span><a href={links['aron.software']}>aron.software ↗</a></div></footer>}
function LegacyHashes(){const {pathname,hash}=useLocation();const map:Record<string,string>={about:'/about',expertise:'/about#expertise',skills:'/about#skills',community:'/about#community',experience:'/experience',contact:'/contact',projects:'/projects'};if(pathname==='/'&&map[hash.slice(1)])return <Navigate to={map[hash.slice(1)]} replace/>;return null}
export default function App(){return <BrowserRouter><div className="modern-site"><IntroLoader/><SpaceCharacter/><RouteEffects/><SiteMotion/><LegacyHashes/><a href="#page-content" className="skip-link">Skip to content</a><Header/><main id="page-content" tabIndex={-1}><Routes><Route path="/" element={<Home/>}/><Route path="/projects" element={<ProjectsPage/>}/><Route path="/projects/:slug" element={<ProjectPage/>}/><Route path="/about" element={<AboutPage/>}/><Route path="/experience" element={<ExperiencePage/>}/><Route path="/contact" element={<ContactPage/>}/><Route path="*" element={<NotFound/>}/></Routes></main><Footer/></div></BrowserRouter>}
