import { Link } from "react-router-dom";
import {useRef, useState, type ReactNode} from 'react';
import {motion, useScroll, useTransform, useReducedMotion, type MotionValue} from 'framer-motion';
import {ArrowUpRight, ArrowLeft, ArrowRight, ArrowDown, Plus, Code2, Smartphone, Layers, Coffee, Github, Linkedin} from 'lucide-react';
import content from './content.json';
const links:Record<string,string> = content.links;
function FadeIn({children,delay=0,y=30,className=''}:{children:ReactNode;delay?:number;y?:number;className?:string}) {const reduced=useReducedMotion();return <motion.div className={className} initial={reduced?false:{opacity:0,y}} whileInView={{opacity:1,y:0}} viewport={{once:true,margin:'50px',amount:0}} transition={{duration:.7,delay,ease:[.25,.1,.25,1]}}>{children}</motion.div>}
function ContactButton({email=false}:{email?:boolean}){return <a className="contact-button" href={email?'mailto:rl.aaron4@gmail.com':'#contact'}>{email?'Email Aaron':"Let’s talk"}<ArrowUpRight size={18}/></a>}
function Magnet({children}:{children:ReactNode}) {const ref=useRef<HTMLDivElement>(null);const [position,setPosition]=useState({x:0,y:0});const reduced=useReducedMotion();return <div ref={ref} onPointerMove={e=>{if(reduced||e.pointerType!=='mouse')return;const r=ref.current!.getBoundingClientRect();setPosition({x:(e.clientX-r.left-r.width/2)/3,y:(e.clientY-r.top-r.height/2)/3})}} onPointerLeave={()=>setPosition({x:0,y:0})} style={{transform:`translate3d(${position.x}px,${position.y}px,0)`,transition:'transform .6s ease-out',willChange:'transform'}}>{children}</div>}
function Character({c,i,total,progress}:{c:string;i:number;total:number;progress:MotionValue<number>}){const opacity=useTransform(progress,[i/total,(i+1)/total],[.2,1]);return <span className="character"><span aria-hidden="true" className="opacity-20">{c}</span><motion.span aria-hidden="true" style={{opacity}} className="absolute inset-0">{c}</motion.span></span>}
function AnimatedText(){const ref=useRef<HTMLParagraphElement>(null);const {scrollYProgress}=useScroll({target:ref,offset:['start 0.8','end 0.2']});const reduced=useReducedMotion();const text="I’ve spent a decade building mobile products, from web and hybrid apps to leading React Native development for enterprise teams. My work spans Walmart’s warehouse tools, HCSC’s member experiences, and IBM’s work with American Electric Power. I care about clean architecture, reliable performance, and helping teams ship software people can depend on.";let index=0;return <p ref={ref} className="about-copy">{!reduced&&<span className="sr-only">{text}</span>}{reduced?text:text.split(' ').map((word,w)=><span key={w} className="inline-block" aria-hidden="true">{(word+'\u00a0').split('').map(c=><Character key={index} c={c} i={index++} total={text.length+1} progress={scrollYProgress}/>)}</span>)}</p>}
export const services=[['React Native & Frontend Development','Building enterprise iOS, Android, and web applications with React Native, Expo, EAS, React, and TypeScript.'],['Mobile Architecture','Designing maintainable application structures, state management, and integrations with enterprise systems.'],['Performance Optimization','Improving startup times, interface responsiveness, and stability across devices.'],['Technical Leadership','Leading development teams, mentoring engineers, and translating product requirements into practical delivery plans.'],['Backend & Cloud Integration','Connecting mobile applications with Node.js, Firebase, Azure, REST APIs, and GraphQL and WebSocket services.']];
export const projects=[{"name": "American Electric Power", "company": "IBM / AEP", "type": "Enterprise field operations", "metric": "40%", "metricLabel": "Faster application load times", "sub": "Less downtime in the field.", "desc": "Built React and React Native workflows integrating 10+ microservice APIs. Performance optimization cut load times by 40%, while Dynatrace instrumentation reduced P1 incident MTTR by 50%.", "tags": ["React Native", "Redux", "Dynatrace"], "detail": 1, "color": "violet"}, {"name": "Receiving 1.0 & 2.0", "company": "Walmart", "type": "Enterprise mobile", "metric": "1,000+", "metricLabel": "Associates using it daily", "sub": "Shared components. Live inventory.", "desc": "Built inventory apps used across hundreds of stores. A shared component system cut duplicate code by 40%, with sub-second SAP data sync and 99.9% crash-free sessions.", "tags": ["React Native", "SAP", "Dynatrace"], "detail": 4, "color": "blue"}, {"name": "HCSC Mobile 2.0", "company": "Infosys / HCSC", "type": "Healthcare mobile", "metric": "85%", "metricLabel": "Code coverage, up from 45%", "sub": "Better code. Better teams.", "desc": "Led React Native delivery for an app serving 1M+ Illinois members. Mentored 4 engineers, improved team velocity by 25%, and established Jest testing standards.", "tags": ["Redux Saga", "Jest", "Mentoring"], "detail": 3, "color": "orange"}, {"name": "Seller Center", "company": "Walmart", "type": "Marketplace platform", "metric": "3", "metricLabel": "Product teams adopting shared standards", "sub": "A foundation for marketplace teams.", "desc": "Spearheaded React Native and React development for Seller Center, supporting billions in annual GMV. Set architecture and review standards for 6+ engineers and established shared libraries across 3 teams.", "tags": ["React", "React Native", "Architecture"], "detail": 0, "color": "blue"}];
export function ProjectSlider(){
  const [active,setActive]=useState(0);
  const touchStart=useRef<number|null>(null);
  const reduced=useReducedMotion();
  const p=projects[active];
  const move=(delta:number)=>setActive(current=>(current+delta+projects.length)%projects.length);
  return <section id="projects" className="project-slider section" aria-label="Selected projects" aria-roledescription="carousel">
    <div className="slider-header"><div><p className="eyebrow">A FEW THINGS I’VE HELPED BUILD</p><h2 className="hero-heading">Selected projects</h2></div><div className="slider-controls"><button type="button" aria-label="Previous project" onClick={()=>move(-1)}><ArrowLeft size={21}/></button><span aria-live="polite" aria-atomic="true">0{active+1} / 0{projects.length}</span><button type="button" aria-label="Next project" onClick={()=>move(1)}><ArrowRight size={21}/></button></div></div>
    <div className="slider-viewport" onTouchStart={e=>{touchStart.current=e.touches[0].clientX}} onTouchEnd={e=>{if(touchStart.current===null)return;const distance=e.changedTouches[0].clientX-touchStart.current;touchStart.current=null;if(Math.abs(distance)>60)move(distance<0?1:-1)}} onTouchCancel={()=>{touchStart.current=null}}>
      <motion.article key={p.name} className={`project-slide ${p.color}`} role="group" aria-roledescription="slide" aria-label={`${active+1} of ${projects.length}: ${p.name}`} initial={reduced?false:{opacity:0,x:25}} animate={{opacity:1,x:0}} transition={{duration:.3}}>
        <div className="slide-visual"><span className="eyebrow">{p.company}</span><div className="slide-metric"><strong>{p.metric}</strong><span>{p.metricLabel}</span></div><div className="slide-diagram" aria-hidden="true"><Smartphone/><span/><Layers/><span/><Code2/></div><span className="slide-index" aria-hidden="true">0{active+1}</span></div>
        <div className="slide-copy"><p className="eyebrow">{p.type}</p><h3>{p.name}</h3><h4>{p.sub}</h4><p className="slide-description">{p.desc}</p><div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div><Link className="slide-link" to={`/projects/${['american-electric-power','walmart-receiving','hcsc','walmart-seller-center'][active]}`}>View project <ArrowUpRight size={18}/></Link></div>
      </motion.article>
    </div>
    <div className="slider-pagination" aria-label="Choose a project">{projects.map((project,i)=><button key={project.name} type="button" aria-label={`Show ${project.name}`} aria-current={i===active?'true':undefined} onClick={()=>setActive(i)}><span className="slider-progress"/><span className="slider-project-name">0{i+1} / {project.company}</span></button>)}</div>
  </section>
}
export function Marquee(){const ref=useRef<HTMLElement>(null);const {scrollYProgress}=useScroll({target:ref,offset:['start end','end start']});const x=useTransform(scrollYProgress,[0,1],[-400,0]);const x2=useTransform(scrollYProgress,[0,1],[0,-400]);const reduced=useReducedMotion();return <section className="marquees" ref={ref} aria-label="Companies and technologies">{[['IBM Consulting','Walmart Global Tech','HCSC','Roambee','Eurybia Studio','American Electric Power'],['React Native','TypeScript','Expo','Redux','Node.js','Firebase','Azure','Dynatrace']].map((row,i)=><motion.div key={i} className={`marquee-row row-${i}`} style={{x:reduced?0:i?x2:x}}>{[0,1,2].map(copy=>row.map(t=><span key={`${copy}-${t}`} aria-hidden={copy>0?true:undefined}>{t}<span className="spark">✳</span></span>))}</motion.div>)}</section>}
