import {useEffect,useRef,useState} from 'react';
import {Link} from 'react-router-dom';
import {ArrowDown,ArrowUpRight,Pause,Play,RotateCw,MoveUp,Orbit} from 'lucide-react';
import {useReducedMotion} from 'framer-motion';
import './CharacterHero.css';
const modes=[{name:'Zero gravity',pose:'fly',icon:Orbit},{name:'Jump',pose:'float',icon:MoveUp},{name:'Barrel roll',pose:'roll',icon:RotateCw}];
export function Pose({name='fly',className=''}:{name?:string;className?:string}){return <img className={`aaron-pose ${className}`} src={`/characters/${name}.webp`} alt="Aaron’s illustrated astronaut character" width="600" height="600" loading="lazy"/>}
export default function CharacterHero(){
 const reduced=useReducedMotion();const [mode,setMode]=useState(0),[paused,setPaused]=useState(false),[replay,setReplay]=useState(0);const scene=useRef<HTMLDivElement>(null);const [visible,setVisible]=useState(true);
 useEffect(()=>{const el=scene.current;if(!el)return;const io=new IntersectionObserver(([entry])=>setVisible(entry.isIntersecting));io.observe(el);return()=>io.disconnect()},[]);
 const still=paused||reduced||!visible;
 return <section className={`space-hero ${still?'space-still':''}`} aria-labelledby="space-title"><div className="space-stars" aria-hidden="true">{Array.from({length:45},(_,i)=><i key={i} style={{left:`${(i*37+3)%100}%`,top:`${(i*17+7)%100}%`,animationDelay:`-${i%7}s`}}/>)}</div><div className="space-hero-copy"><span className="space-signal"><i/> PLAYER ONE HAS ENTERED</span><p className="space-identity">Aaron David Ramírez Lezama<br/>React Native & Frontend Engineer</p><h1 id="space-title">Built for<br/><em>the next</em><br/>big leap<span>.</span></h1><p className="space-description">I turn ambitious ideas into mobile and web products. 10+ years building, leading, and exploring what comes next.</p><Link className="space-work" to="/#professional-apps">Explore my work <ArrowDown size={20}/></Link></div><div ref={scene} className="space-stage" onPointerMove={e=>{if(still||e.pointerType!=='mouse')return;const r=e.currentTarget.getBoundingClientRect();e.currentTarget.style.setProperty('--px',`${((e.clientX-r.left)/r.width-.5)*22}px`);e.currentTarget.style.setProperty('--py',`${((e.clientY-r.top)/r.height-.5)*22}px`)}} onPointerLeave={e=>{e.currentTarget.style.setProperty('--px','0px');e.currentTarget.style.setProperty('--py','0px')}}><div className="space-orbit orbit-one"/><div className="space-orbit orbit-two"/><div className="space-planet"/><span className="space-coordinate">AR—01<br/>EXPLORATION MODE</span><span className="space-coordinate bottom">REACT NATIVE / TYPESCRIPT<br/>EARTH → WHAT’S NEXT</span><div className="space-actor-parallax"><div key={`${mode}-${replay}`} className={`space-actor move-${mode}`}><img src={`/characters/${modes[mode].pose}.webp`} width="600" height="600" alt={`Aaron in ${modes[mode].name.toLowerCase()} mode`} fetchPriority="high"/></div></div><span className="space-satellite satellite-one">&lt;/&gt;</span><span className="space-satellite satellite-two">✦</span><div className="space-controls"><span>TAKE THE CONTROLS</span><div>{modes.map(({name,icon:Icon},i)=><button key={name} aria-pressed={mode===i} onClick={()=>{setMode(i);setReplay(n=>n+1)}}><Icon size={15}/>{name}</button>)}<button aria-label={paused?'Resume hero animation':'Pause hero animation'} onClick={()=>setPaused(p=>!p)}>{paused?<Play size={16}/>:<Pause size={16}/>}</button></div></div></div><div className="space-hero-bottom"><span>MOBILE · WEB · COMMUNITY</span><Link to="/experience">VIEW MISSION LOG <ArrowUpRight size={14}/></Link><span>SCROLL TO EXPLORE ↓</span></div></section>
}
export function PosePlayground(){const [pose,setPose]=useState('smile');return <section className="pose-playground"><div><span className="game-eyebrow">SAME AARON. DIFFERENT ENERGY.</span><h2>Pick a pose.<br/>Meet the person.</h2><p>Curious by default. Always up for a new challenge.</p><div className="pose-choices">{[['smile','Say hello'],['fly','Explore'],['float','Celebrate'],['roll','Mix it up'],['sit','Recharge'],['land','Ready to build']].map(([p,label])=><button key={p} onClick={()=>setPose(p)} aria-pressed={pose===p}>{label}</button>)}</div></div><div className="pose-playground-stage"><Pose key={pose} name={pose}/><span className="character-platform"/></div></section>}
export function CharacterCheckpoint({kind='land',label='NEXT MISSION',title='Ready for what’s next?'}:{kind?:string;label?:string;title?:string}){return <div className="character-checkpoint"><Pose name={kind}/><div><span className="game-eyebrow">{label}</span><h2>{title}</h2></div><span className="checkpoint-orbit" aria-hidden="true"/></div>}
